/*
 * This source file was generated by the Gradle 'init' task
 */
package ai.indygen.tests;

import ai.indygen.dev.TestApp;
import org.testng.Assert;

public class AppTest {
//    @Test 
    public void test01_validateHelloWorld() {
        TestApp classUnderTest = new TestApp();
        String sExpectedMsg = "Hello World!";
        Assert.assertEquals(classUnderTest.getHelloWorld(), sExpectedMsg);
    }
//    @Test 
    public void test02_validatePostiveInt() {
        TestApp classUnderTest = new TestApp();
        Assert.assertEquals(classUnderTest.getPostiveIntValue(), 10);
    }
}
