/*
 * This source file was generated by the Gradle 'init' task
 */
package ai.indygen.dev;

public class TestApp {
    public boolean getTrueValue () {
        return true;
    }
    public boolean getFalseValue () {
        return false;
    }

    public String getHelloWorld () {
        return "Hello World!";
    }

    public int getPostiveIntValue () {
        return 10;
    }

    public String getNullValue () {
        return null;
    }

    public static void main (String[] args){
        
    }
}
